### ISSUE TITLE
Object transformations returns 'tables'

### ISSUE THREAD

**Issue by akira28** [stone-payments/kong-plugin-template-transformer#154]
### Issue Description

using this template for the response:

```
{
    "zoo": {{body.headers}}
}
```

with this original response
```
{
    "headers": {
      "foo": "bar"
    }
}
```

I receive

```
{
    "zoo": table: 0x7f6068eacdd0
}
```

### Expected Behavior

I receive

```
{
    "zoo": {
      "foo": "bar"
    }
}
```

**Comment by jonathanlazaro1** [comment]
@akira28 , thanks for submitting this issue!

To achieve what you want, you need to use the function `cjson_encode`, like this:
```
{
  "zoo": {{cjson_encode(body.headers)}}
}
```

**Comment by akira28** [comment]
great, thanks! I think some more complex examples would be useful for new users of your plug-in 🙂

**Comment by akira28** [comment]
Tried it and it works as a charm. Thanks!

**Comment by jonathanlazaro1** [comment]
@akira28 , you're totally right. We'll try and bring more advanced use cases to the examples folder. Thanks again!
