### ISSUE TITLE
Apply template to response only on 2xx status codes

### ISSUE THREAD

**Issue by akira28** [stone-payments/kong-plugin-template-transformer#155]
### Issue Description
If I receive a 4xx or 5xx from the internal service, the format would be totally different from a 2xx response. It would be nice to have an option to activate templates only on 2xx status.

### Expected Behavior

If i receive a 5xx or 4xx from the internal service, I don't apply any transformation, if I passed a specific option when I create the plugin (something like `--apply-only-on-success=true`, or `--apply-for-status=200`)

**Comment by jonathanlazaro1** [comment]
Hi, @akira28 !

While we currently don't have an automated way to do as you suggest, there's a workaround you can apply directly to the template, like this:

```
{% if status == 200 then %}
{
  "data": {
    "transformed_field_1": "{{body.field1}}",
  }
  "errors": null
}
{% else %}
{
    "data" : null,
    "errors": "{{body.errors}}"
}
{% end %}
```
NOTE: You can, of course, use `{% elseif _____ %}` to check for other status codes and/or conditions.

Feel free to mention me if you have any further questions.

**Comment by akira28** [comment]
for people having the same question, the correct snippet would be:
```
{% if {{status}} == 200 then %}
{
  "data": {
    "transformed_field_1": "{{body.field1}}",
  }
  "errors": null
}
{% else %}
{{cjson_encode(body)}}
{% end %}
```

(note the `{{status}}` instead of directly `status`)
