### ISSUE TITLE
Version 1.1.0 is not available at LuaRocks

### ISSUE THREAD

**Issue by akira28** [stone-payments/kong-plugin-template-transformer#160]
### Issue Description
I'm trying to install the latest version of the plugin 1.1.0 but it's not available at https://luarocks.org/modules/stone-payments/kong-plugin-template-transformer: `luarocks install kong-plugin-template-transformer 1.1.0-0`. When trying it fails with this error:
```
Error: No results matching query were found for Lua 5.1.
To check if it is available for other Lua versions, use --check-lua-versions.
```
I even tried to use the git repo with no success:
`luarocks install https://raw.githubusercontent.com/stone-payments/kong-plugin-template-transformer/v1.1.0/rockspec.template`
### Expected Behavior
Plugin is installed successfully running `luarocks install kong-plugin-template-transformer 1.1.0-0`

**Comment by akira28** [comment]
hey @jonathanlazaro1 let me know if I can help in any way with this (sorry for bugging you :P )

**Comment by jonathanlazaro1** [comment]
Hi @akira28 ! Sorry for the reaaally late reply :smiling_face_with_tear: . We've had a problem with our automated LuaRocks deploy process, so I uploaded it manually today while we look for a better solution.

**Comment by akira28** [comment]
don't worry, I found a workaround in the meantime. Once I get back to work I'll remove the workaround. Thanks!
