### ISSUE TITLE
Advertising this plugin to the Kong community?

### ISSUE THREAD

**Issue by thibaultcha** [stone-payments/kong-plugin-template-transformer#72]
Hello,

Good job on the plugin!

Have you given some thought about advertising your plugin to the Kong community? You could submit it for publication to the [Kong Hub](https://docs.konghq.com/hub/) (learn how to do so [here](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#kong-hub-contributions) - contact.
If you are not interested in publishing this plugin to the Hub, you may consider posting an announcement on our community forum, [Kong Nation](https://discuss.konghq.com/c/announcements) as well.

Best,

**Comment by PFadel** [comment]
Hello @thibaultcha , I believe we're [already at Kong Kub](https://docs.konghq.com/hub/stone-payments/kong-plugin-template-transformer/).

Thanks anyway!

**Comment by thibaultcha** [comment]
Oh, awesome! My bad, good job :+1:
