### ISSUE TITLE
Unable to translate response containing json array

### ISSUE THREAD

**Issue by AnirudhaPatil** [stone-payments/kong-plugin-template-transformer#75]
### Issue Description

Hello, 
I was wondering whether template transformer plugin can translate response containing json array.

I have a case, where api response returns an array of json objects.
e.g;
```
[{
    "_id": 1,
    "firstName": "abc",
    "lastName": "xyz",
    "email": "abc.xyz@gmail.com",
    "role_id": [{
        "_id": 1,
        "name": "Administrator",
        "description": "All Access"
      }
    ]
  }
]
```

From the response above, I want to remove field '_id' via template transformer. But it still returns what I set treating the response as simple object (not like array).

I suspect that plugin is unable to understand that response is in array format.

### Expected Behavior

RESPONSE VALUE: 
```
[{
    "_id": 1,
    "firstName": "abc",
    "lastName": "xyz",
    "email": "abc.xyz@gmail.com",
    "role_id": [{
        "_id": 1,
        "name": "Administrator",
        "description": "All Access"
      }
    ]
  }
]
```

RESPONSE-TEMPLATE:
```
{
	"firstName": "{{body.firstName}}",
	"lastName": "{{body.lastName}}",
	"email": "{{body.email}}"
}
```

EXPECTED RESULT: 
```
{
	"firstName": "abc",
	"lastName": "xyz",
	"email": "abc.xyz@gmail.com"
}
```

**Comment by PFadel** [comment]
Hello @AnirudhaPatil , since your body is an array you have to iterate over it in the response template.

Something like this:

```
{% for i, object in ipairs(body) do %}
{
    "{{object.firstName}}",
    "{{object.lastName}}",
    "{{object.email}}"
}
{% end %}
```

Just be careful with commas! This line of code at the end of the object usually helps:

```
{% if i ~= #body then %},{% end %}
```

**Comment by PFadel** [comment]
Closing this for lack of response and I believe it was answered.
