### ISSUE TITLE
Compatibility with Kong 1.x

### ISSUE THREAD

**Issue by eurodomenii** [stone-payments/kong-plugin-template-transformer#80]
Due to limited functionality of  kong bundled request transformer , this plugin is life-saving.  Any ETA for Kong 1.x compatibility?

**Comment by eurodomenii** [comment]
Thanks for quick feedback https://github.com/stone-payments/kong-plugin-template-transformer/releases/tag/v0.10.0  " Add Kong 1 support by removing kong.errors.dao"

**Comment by PFadel** [comment]
No problem @eurodomenii ! Please feel free to reopen this if you have any issues.
